change data reviewer link to data approval link
EyeSeeTea/data-management-app pull request #468
Opened 2022-09-07 14:21 UTC by deeonwuli

### :pushpin: References

* **Issue:** Closes https://app.clickup.com/t/3dfg9gc

### :art: Screenshots
<img width="451" alt="Screenshot 2022-09-07 at 15 20 50" src="https://user-images.githubusercontent.com/37223065/188902159-f8d63ea2-2cb6-4cf1-8b95-21d9d5c2d02e.png">

2022-09-12 19:55 UTC, adrianq commented
@deeonwuli Does the data approval URL exist? I am getting this URL:
http://localhost:8080/data-approval/HPGEAQ1dPJQ/actual/202208
while I should be getting something like:
http://localhost:8080/api/apps/Data-Management-App/index.html#/data-approval/HPGEAQ1dPJQ/actual/202208

Can you please have a look at this tomorrow morning? We are aiming to deploy this new version tomorrow

2022-09-13 09:27 UTC, tokland requested changes

2022-09-13 09:27 UTC, tokland commented on src/models/ProjectNotification.ts
> +
We have `getUrl` as an example of how to generate programmatically the route and make it work for DEV and APP (with features involving links, check always that the app works). I've sent you a proposal, check it and upload with the changes you see fit.

2022-09-13 11:24 UTC, tokland approved these changes
All good!

2022-09-13 12:32 UTC, adrianq commented
Thanks!

2022-09-13 12:32 UTC, merged